import type { Metadata } from "next";
import {
  ClerkProvider,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import ConvexClientProvider from "./ConvexClientProvider";
import AddUserToDb from "@/lib/AddUserToDb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <AddUserToDb />
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="flex justify-around items-center p-4 h-16 bg-black">
              <Link
                href="/"
                className="text-black text-xl font-serif rounded-full bg-white p-1">
                HA
              </Link>
              <span className="text-white text-xl font-serif">RemO.AI</span>
              <SignedOut>
                <SignUpButton>
                  <Button>Sign in</Button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton
                  fallback={
                    <div
                      className="size-7 bg-gray-600 animate-pulse rounded-full"
                      aria-labelledby="Loading please wait.."
                    />
                  }
                />
              </SignedIn>
            </header>
            {children}
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
